# Use root/example as user/password credentials
version: '3.1'
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: nike
      #WAIT_HOSTS: mongodb:27017
    volumes:
      - ./database/:/home/database
    ports:
      - 27017:27017
    #command: bash -c "chmod +x /databases/db/wait-for-it.sh && /databases/db/wait-for-it.sh --timeout=0 localhost:27017"


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
