version: '3.1'
services:
  webserver:
    container_name: web_server
    image: bot_web_server/node-web-app
    restart: always
    networks:
      - mongodb_bot-network
    volumes:
      - ./:/home/database
    ports:
      - 4000:8080

networks:
  mongodb_bot-network:
    external: true